[bumpver]
current_version = "0.1.4"
version_pattern = "MAJOR.MINOR.PATCH"
commit = true
tag = true
push = true
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "global"

[bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"'
]
"app/config/app_config.py" = [
    '__version__ = "{version}"'
]